### ISSUE TITLE
Initial idea

### ISSUE THREAD

**Issue by sobolevn** [mimesis-lab/mimesis-factory#1]
I have spent an hour to make `mimesis` and `factory_boy` work together.
@lk-geimfari do you like my approach?

I have created a gist as a proof of a concept: https://gist.github.com/sobolevn/19032ff9ed03a167a3cc3337ebaebd99

**Comment by lk-geimfari** [comment]
@sobolevn Sure! Looks awesome. I'll try how it works right now.
