### ISSUE TITLE
Support mimesis 4.х

### ISSUE THREAD

**Issue by ditansu** [mimesis-lab/mimesis-factory#148]
@sobolevn please add support mimesis 4.х

**Comment by sobolevn** [comment]
This package totally needs some love. Thanks a lot! Will do shortly.

**Comment by sobolevn** [comment]
I have started with `pytest-mimesis`: https://github.com/pytest-dev/pytest-mimesis/pull/79

The next goal is to update this project as well.

**Comment by sobolevn** [comment]
`1.1.0` is published! Thanks!
