### ISSUE TITLE
Change base class

### ISSUE THREAD

**Issue by sobolevn** [mimesis-lab/mimesis-factory#2]
New version (2.9) of `factory_boy` uses different base class for custom fields.

We are using `OrderedDeclaration` https://github.com/mimesis-lab/mimesis-factory/blob/master/mimesis_factory/main.py#L5

While the new version is using `BaseDeclaration`.

There are two possible ways:
1. To drop 2.8 support (is was initially made this way to make `pytest-factoryboy` work
2. To support both versions and choose base class conditionally 
3. Find something we can safely inherit from

**Comment by lk-geimfari** [comment]
@sobolevn What do you think about it? Should we support both versions?

**Comment by sobolevn** [comment]
I don't know, it depends on what versions are the most popular.

**Comment by lk-geimfari** [comment]
@sobolevn Seems like [2.8.1](http://www.pypi-stats.com/package/?q=factory_boy).
