### ISSUE TITLE
Move mimesis_factory to mimesis.plugins

### ISSUE THREAD

**Issue by lk-geimfari** [mimesis-lab/mimesis-factory#246]
Starting from Mimesis version 15.0.0, this package will become a part of Mimesis. Once this transition is completed, this repository will be archived.

### Rationale
This will help us always keep this package up-to-date.

### Deps

Mimesis will still remain dependency-free. To utilize this plugin, developers will need to install factory_boy explicitly.

### Usage
Here is an example of usage:

```python
import factory
from mimesis.plugins.factory import MimesisField

from account import Account


class AccountFactory(factory.Factory):
    class Meta(object):
        model = Account

    username = MimesisField('username', template='l_d')
    name = MimesisField('name', gender='female')
    surname = MimesisField('surname', gender='female')
    age = MimesisField('age', minimum=18, maximum=90)
    email = factory.LazyAttribute(
        lambda instance: '{0}@example.org'.format(instance.username)
    )
    access_token = MimesisField('token', entropy=32)
```

### For discussion purposes
One thing I'm not sure about is the class name. Should we keep `MimesisField`, or perhaps use something like `FactoryField`?

**Comment by lk-geimfari** [comment]
@sobolevn What do you think?

**Comment by sobolevn** [comment]
I agree, plus you can add `mimesis[factory]` extra to ship supported `factory_boy` version.

**Comment by lk-geimfari** [comment]
So, it's done in 15.1.0.
