### ISSUE TITLE
Inheritance of providers override attributes of the superclass.

### ISSUE THREAD

**Issue by lk-geimfari** [mimesis-lab/mimesis-factory#6]
It's happening for some classes because we use this:

```python
class LocaleDepProvider(Address, Business, Code, Datetime,
                        Personal, Science, Text, Food):
    pass


class CommonProvider(ClothingSizes, Development, File, Hardware,
                     Internet, Numbers, Path, Structured, Transport,
                     UnitSystem, Games, Cryptographic):
    pass


class Provider(LocaleDepProvider, CommonProvider):
    pass
```

Where each class has attribute `self._data`. Given how the inheritance tree works, errors are possible.

**Comment by sobolevn** [comment]
This will have issues. 

What's the point in `LocaleDepProvider`? 
What are you trying to achieve?

**Comment by sobolevn** [comment]
Can you please cover my initial questions?

> What's the point in LocaleDepProvider?
> What are you trying to achieve?

Right now I don't understand a purpose of these classes, so I cant suggest any other alternatives.

**Comment by lk-geimfari** [comment]
@sobolevn Check out skype, please.

**Comment by sobolevn** [comment]
Closing as invalid.
