### ISSUE TITLE
Cannot install from source to get latest features

### ISSUE THREAD

**Issue by mjhoffman65** [mimesis-lab/mimesis-factory#72]
Is there any way to install this from source using pip?  I would like to use some of the provider functionality that has been added in since the 0.1.0 release last June.  I tried 
```
pip install -e git+https://github.com/mimesis-lab/mimesis-factory.git#egg=mimesis_factory
```
, but it is failing because there is no `setup.py` in the repository.  This is the error I got:
```
$ pip install -e git+https://github.com/mimesis-lab/mimesis-factory.git#egg=mimesis_factory
Obtaining mimesis_factory from git+https://github.com/mimesis-lab/mimesis-factory.git#egg=mimesis_factory
  Cloning https://github.com/mimesis-lab/mimesis-factory.git to /home/matt/virtualenvs/stream/src/mimesis-factory
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/matt/virtualenvs/stream/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/home/matt/virtualenvs/stream/src/mimesis-factory/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/matt/virtualenvs/stream/src/mimesis-factory/
```

What is the recommended way to install a more recent version of mimesis-factory?  I'd be happy to help out if the solution is to add a `setup.py`.

**Comment by sobolevn** [comment]
@mjhoffman65 well, since we are using `poetry` there's no need in `setup.py`.

We need to make a new release. I will take a look at this project tomorrow. 
And hopefully make a release. Thanks for bringing this up!

**Comment by sobolevn** [comment]
`1.0.0` is released. @mjhoffman65 thanks a lot! 👍

**Comment by sobolevn** [comment]
Please, open new issues if you encounter any other problems.
